-- Data contoh (September 2026 + 5 bulan sebelumnya). Jalankan HANYA di database baru
-- yang baru saja menjalankan db.sql: npm run db:seed
BEGIN;
UPDATE wallets SET opening_balance = 300000 WHERE kind='cash';
UPDATE wallets SET opening_balance = 4300000 WHERE kind='bank';
UPDATE wallets SET opening_balance = 200000 WHERE kind='ewallet';
INSERT INTO transactions (type, amount, category_id, wallet_id, date, note) VALUES
  ('income',7500000,(SELECT id FROM categories WHERE name='Gaji' AND type='income'),(SELECT id FROM wallets WHERE kind='bank' ORDER BY id LIMIT 1),'2026-09-01','Gaji bulanan'),
  ('expense',120000,(SELECT id FROM categories WHERE name='Makan' AND type='expense'),(SELECT id FROM wallets WHERE kind='ewallet' ORDER BY id LIMIT 1),'2026-09-01','Makan siang'),
  ('expense',150000,(SELECT id FROM categories WHERE name='Transport' AND type='expense'),(SELECT id FROM wallets WHERE kind='ewallet' ORDER BY id LIMIT 1),'2026-09-02','Ojek online'),
  ('expense',130000,(SELECT id FROM categories WHERE name='Makan' AND type='expense'),(SELECT id FROM wallets WHERE kind='ewallet' ORDER BY id LIMIT 1),'2026-09-03','Sarapan'),
  ('expense',210000,(SELECT id FROM categories WHERE name='Belanja' AND type='expense'),(SELECT id FROM wallets WHERE kind='bank' ORDER BY id LIMIT 1),'2026-09-04','Perlengkapan rumah'),
  ('expense',140000,(SELECT id FROM categories WHERE name='Makan' AND type='expense'),(SELECT id FROM wallets WHERE kind='ewallet' ORDER BY id LIMIT 1),'2026-09-05','Makan malam'),
  ('expense',58000,(SELECT id FROM categories WHERE name='Hiburan' AND type='expense'),(SELECT id FROM wallets WHERE kind='ewallet' ORDER BY id LIMIT 1),'2026-09-06','Nonton bioskop'),
  ('expense',95000,(SELECT id FROM categories WHERE name='Tagihan' AND type='expense'),(SELECT id FROM wallets WHERE kind='bank' ORDER BY id LIMIT 1),'2026-09-07','Air'),
  ('expense',260000,(SELECT id FROM categories WHERE name='Makan' AND type='expense'),(SELECT id FROM wallets WHERE kind='cash' ORDER BY id LIMIT 1),'2026-09-08','Kopi dan camilan'),
  ('expense',110000,(SELECT id FROM categories WHERE name='Transport' AND type='expense'),(SELECT id FROM wallets WHERE kind='ewallet' ORDER BY id LIMIT 1),'2026-09-09','Bensin'),
  ('expense',170000,(SELECT id FROM categories WHERE name='Belanja' AND type='expense'),(SELECT id FROM wallets WHERE kind='bank' ORDER BY id LIMIT 1),'2026-09-10','Beli baju'),
  ('expense',120000,(SELECT id FROM categories WHERE name='Hiburan' AND type='expense'),(SELECT id FROM wallets WHERE kind='ewallet' ORDER BY id LIMIT 1),'2026-09-11','Game'),
  ('expense',230000,(SELECT id FROM categories WHERE name='Makan' AND type='expense'),(SELECT id FROM wallets WHERE kind='cash' ORDER BY id LIMIT 1),'2026-09-12','Makan bareng teman'),
  ('expense',140000,(SELECT id FROM categories WHERE name='Makan' AND type='expense'),(SELECT id FROM wallets WHERE kind='ewallet' ORDER BY id LIMIT 1),'2026-09-13','Makan siang'),
  ('expense',110000,(SELECT id FROM categories WHERE name='Transport' AND type='expense'),(SELECT id FROM wallets WHERE kind='ewallet' ORDER BY id LIMIT 1),'2026-09-14','Parkir'),
  ('expense',95000,(SELECT id FROM categories WHERE name='Makan' AND type='expense'),(SELECT id FROM wallets WHERE kind='ewallet' ORDER BY id LIMIT 1),'2026-09-15','Sarapan'),
  ('expense',165000,(SELECT id FROM categories WHERE name='Belanja' AND type='expense'),(SELECT id FROM wallets WHERE kind='bank' ORDER BY id LIMIT 1),'2026-09-16','Aksesoris laptop'),
  ('expense',105000,(SELECT id FROM categories WHERE name='Makan' AND type='expense'),(SELECT id FROM wallets WHERE kind='ewallet' ORDER BY id LIMIT 1),'2026-09-16','Makan malam'),
  ('expense',130000,(SELECT id FROM categories WHERE name='Makan' AND type='expense'),(SELECT id FROM wallets WHERE kind='cash' ORDER BY id LIMIT 1),'2026-09-17','Kopi dan camilan'),
  ('expense',230000,(SELECT id FROM categories WHERE name='Hiburan' AND type='expense'),(SELECT id FROM wallets WHERE kind='ewallet' ORDER BY id LIMIT 1),'2026-09-18','Nongkrong'),
  ('expense',85000,(SELECT id FROM categories WHERE name='Tagihan' AND type='expense'),(SELECT id FROM wallets WHERE kind='bank' ORDER BY id LIMIT 1),'2026-09-19','Pulsa dan paket data'),
  ('expense',260000,(SELECT id FROM categories WHERE name='Makan' AND type='expense'),(SELECT id FROM wallets WHERE kind='ewallet' ORDER BY id LIMIT 1),'2026-09-20','Makan bareng teman'),
  ('expense',150000,(SELECT id FROM categories WHERE name='Transport' AND type='expense'),(SELECT id FROM wallets WHERE kind='ewallet' ORDER BY id LIMIT 1),'2026-09-21','Tiket kereta'),
  ('expense',160000,(SELECT id FROM categories WHERE name='Tagihan' AND type='expense'),(SELECT id FROM wallets WHERE kind='bank' ORDER BY id LIMIT 1),'2026-09-22','Iuran lingkungan'),
  ('expense',168000,(SELECT id FROM categories WHERE name='Hiburan' AND type='expense'),(SELECT id FROM wallets WHERE kind='ewallet' ORDER BY id LIMIT 1),'2026-09-23','Langganan musik'),
  ('expense',32000,(SELECT id FROM categories WHERE name='Tagihan' AND type='expense'),(SELECT id FROM wallets WHERE kind='bank' ORDER BY id LIMIT 1),'2026-09-23','Air'),
  ('expense',90000,(SELECT id FROM categories WHERE name='Makan' AND type='expense'),(SELECT id FROM wallets WHERE kind='cash' ORDER BY id LIMIT 1),'2026-09-24','Makan siang'),
  ('expense',70000,(SELECT id FROM categories WHERE name='Tagihan' AND type='expense'),(SELECT id FROM wallets WHERE kind='bank' ORDER BY id LIMIT 1),'2026-09-24','Pulsa dan paket data'),
  ('expense',610000,(SELECT id FROM categories WHERE name='Tagihan' AND type='expense'),(SELECT id FROM wallets WHERE kind='bank' ORDER BY id LIMIT 1),'2026-09-25','Tagihan listrik & internet'),
  ('expense',170000,(SELECT id FROM categories WHERE name='Transport' AND type='expense'),(SELECT id FROM wallets WHERE kind='ewallet' ORDER BY id LIMIT 1),'2026-09-26','Ojek online'),
  ('expense',32000,(SELECT id FROM categories WHERE name='Transport' AND type='expense'),(SELECT id FROM wallets WHERE kind='ewallet' ORDER BY id LIMIT 1),'2026-09-27','Bensin'),
  ('expense',198000,(SELECT id FROM categories WHERE name='Tagihan' AND type='expense'),(SELECT id FROM wallets WHERE kind='bank' ORDER BY id LIMIT 1),'2026-09-27','Iuran lingkungan'),
  ('expense',54000,(SELECT id FROM categories WHERE name='Hiburan' AND type='expense'),(SELECT id FROM wallets WHERE kind='ewallet' ORDER BY id LIMIT 1),'2026-09-28','Langganan streaming'),
  ('expense',76000,(SELECT id FROM categories WHERE name='Transport' AND type='expense'),(SELECT id FROM wallets WHERE kind='ewallet' ORDER BY id LIMIT 1),'2026-09-28','Ojek online'),
  ('income',1000000,(SELECT id FROM categories WHERE name='Freelance' AND type='income'),(SELECT id FROM wallets WHERE kind='bank' ORDER BY id LIMIT 1),'2026-09-29','Pembayaran website klien'),
  ('expense',215000,(SELECT id FROM categories WHERE name='Belanja' AND type='expense'),(SELECT id FROM wallets WHERE kind='bank' ORDER BY id LIMIT 1),'2026-09-29','Kebutuhan bulanan'),
  ('expense',45000,(SELECT id FROM categories WHERE name='Makan' AND type='expense'),(SELECT id FROM wallets WHERE kind='cash' ORDER BY id LIMIT 1),'2026-09-29','Makan malam'),
  ('expense',35000,(SELECT id FROM categories WHERE name='Makan' AND type='expense'),(SELECT id FROM wallets WHERE kind='ewallet' ORDER BY id LIMIT 1),'2026-09-30','Makan siang'),
  ('expense',22000,(SELECT id FROM categories WHERE name='Transport' AND type='expense'),(SELECT id FROM wallets WHERE kind='ewallet' ORDER BY id LIMIT 1),'2026-09-30','Ojek ke kantor'),
  ('income',8000000,(SELECT id FROM categories WHERE name='Gaji' AND type='income'),(SELECT id FROM wallets WHERE kind='bank' ORDER BY id LIMIT 1),'2026-04-01','Gaji bulanan'),
  ('expense',1592000,(SELECT id FROM categories WHERE name='Makan' AND type='expense'),(SELECT id FROM wallets WHERE kind='bank' ORDER BY id LIMIT 1),'2026-04-10','Makan bulan 04'),
  ('expense',1228000,(SELECT id FROM categories WHERE name='Tagihan' AND type='expense'),(SELECT id FROM wallets WHERE kind='bank' ORDER BY id LIMIT 1),'2026-04-10','Tagihan bulan 04'),
  ('expense',933000,(SELECT id FROM categories WHERE name='Transport' AND type='expense'),(SELECT id FROM wallets WHERE kind='bank' ORDER BY id LIMIT 1),'2026-04-10','Transport bulan 04'),
  ('expense',1258000,(SELECT id FROM categories WHERE name='Belanja' AND type='expense'),(SELECT id FROM wallets WHERE kind='bank' ORDER BY id LIMIT 1),'2026-04-10','Belanja bulan 04'),
  ('expense',589000,(SELECT id FROM categories WHERE name='Hiburan' AND type='expense'),(SELECT id FROM wallets WHERE kind='bank' ORDER BY id LIMIT 1),'2026-04-10','Hiburan bulan 04'),
  ('income',8200000,(SELECT id FROM categories WHERE name='Gaji' AND type='income'),(SELECT id FROM wallets WHERE kind='bank' ORDER BY id LIMIT 1),'2026-05-01','Gaji bulanan'),
  ('expense',1734000,(SELECT id FROM categories WHERE name='Makan' AND type='expense'),(SELECT id FROM wallets WHERE kind='bank' ORDER BY id LIMIT 1),'2026-05-10','Makan bulan 05'),
  ('expense',1338000,(SELECT id FROM categories WHERE name='Tagihan' AND type='expense'),(SELECT id FROM wallets WHERE kind='bank' ORDER BY id LIMIT 1),'2026-05-10','Tagihan bulan 05'),
  ('expense',1017000,(SELECT id FROM categories WHERE name='Transport' AND type='expense'),(SELECT id FROM wallets WHERE kind='bank' ORDER BY id LIMIT 1),'2026-05-10','Transport bulan 05'),
  ('expense',1370000,(SELECT id FROM categories WHERE name='Belanja' AND type='expense'),(SELECT id FROM wallets WHERE kind='bank' ORDER BY id LIMIT 1),'2026-05-10','Belanja bulan 05'),
  ('expense',641000,(SELECT id FROM categories WHERE name='Hiburan' AND type='expense'),(SELECT id FROM wallets WHERE kind='bank' ORDER BY id LIMIT 1),'2026-05-10','Hiburan bulan 05'),
  ('income',7500000,(SELECT id FROM categories WHERE name='Gaji' AND type='income'),(SELECT id FROM wallets WHERE kind='bank' ORDER BY id LIMIT 1),'2026-06-01','Gaji bulanan'),
  ('expense',1677000,(SELECT id FROM categories WHERE name='Makan' AND type='expense'),(SELECT id FROM wallets WHERE kind='bank' ORDER BY id LIMIT 1),'2026-06-10','Makan bulan 06'),
  ('expense',1294000,(SELECT id FROM categories WHERE name='Tagihan' AND type='expense'),(SELECT id FROM wallets WHERE kind='bank' ORDER BY id LIMIT 1),'2026-06-10','Tagihan bulan 06'),
  ('expense',983000,(SELECT id FROM categories WHERE name='Transport' AND type='expense'),(SELECT id FROM wallets WHERE kind='bank' ORDER BY id LIMIT 1),'2026-06-10','Transport bulan 06'),
  ('expense',1325000,(SELECT id FROM categories WHERE name='Belanja' AND type='expense'),(SELECT id FROM wallets WHERE kind='bank' ORDER BY id LIMIT 1),'2026-06-10','Belanja bulan 06'),
  ('expense',621000,(SELECT id FROM categories WHERE name='Hiburan' AND type='expense'),(SELECT id FROM wallets WHERE kind='bank' ORDER BY id LIMIT 1),'2026-06-10','Hiburan bulan 06'),
  ('income',8500000,(SELECT id FROM categories WHERE name='Gaji' AND type='income'),(SELECT id FROM wallets WHERE kind='bank' ORDER BY id LIMIT 1),'2026-07-01','Gaji bulanan'),
  ('expense',1506000,(SELECT id FROM categories WHERE name='Makan' AND type='expense'),(SELECT id FROM wallets WHERE kind='bank' ORDER BY id LIMIT 1),'2026-07-10','Makan bulan 07'),
  ('expense',1162000,(SELECT id FROM categories WHERE name='Tagihan' AND type='expense'),(SELECT id FROM wallets WHERE kind='bank' ORDER BY id LIMIT 1),'2026-07-10','Tagihan bulan 07'),
  ('expense',883000,(SELECT id FROM categories WHERE name='Transport' AND type='expense'),(SELECT id FROM wallets WHERE kind='bank' ORDER BY id LIMIT 1),'2026-07-10','Transport bulan 07'),
  ('expense',1190000,(SELECT id FROM categories WHERE name='Belanja' AND type='expense'),(SELECT id FROM wallets WHERE kind='bank' ORDER BY id LIMIT 1),'2026-07-10','Belanja bulan 07'),
  ('expense',559000,(SELECT id FROM categories WHERE name='Hiburan' AND type='expense'),(SELECT id FROM wallets WHERE kind='bank' ORDER BY id LIMIT 1),'2026-07-10','Hiburan bulan 07'),
  ('income',8000000,(SELECT id FROM categories WHERE name='Gaji' AND type='income'),(SELECT id FROM wallets WHERE kind='bank' ORDER BY id LIMIT 1),'2026-08-01','Gaji bulanan'),
  ('expense',1620000,(SELECT id FROM categories WHERE name='Makan' AND type='expense'),(SELECT id FROM wallets WHERE kind='bank' ORDER BY id LIMIT 1),'2026-08-10','Makan bulan 08'),
  ('expense',1250000,(SELECT id FROM categories WHERE name='Tagihan' AND type='expense'),(SELECT id FROM wallets WHERE kind='bank' ORDER BY id LIMIT 1),'2026-08-10','Tagihan bulan 08'),
  ('expense',950000,(SELECT id FROM categories WHERE name='Transport' AND type='expense'),(SELECT id FROM wallets WHERE kind='bank' ORDER BY id LIMIT 1),'2026-08-10','Transport bulan 08'),
  ('expense',1280000,(SELECT id FROM categories WHERE name='Belanja' AND type='expense'),(SELECT id FROM wallets WHERE kind='bank' ORDER BY id LIMIT 1),'2026-08-10','Belanja bulan 08'),
  ('expense',600000,(SELECT id FROM categories WHERE name='Hiburan' AND type='expense'),(SELECT id FROM wallets WHERE kind='bank' ORDER BY id LIMIT 1),'2026-08-10','Hiburan bulan 08');
INSERT INTO transfers (from_wallet, to_wallet, amount, date, note) VALUES
  ((SELECT id FROM wallets WHERE kind='bank' ORDER BY id LIMIT 1),(SELECT id FROM wallets WHERE kind='cash' ORDER BY id LIMIT 1),800000,'2026-09-01','Tarik tunai'),
  ((SELECT id FROM wallets WHERE kind='bank' ORDER BY id LIMIT 1),(SELECT id FROM wallets WHERE kind='ewallet' ORDER BY id LIMIT 1),1500000,'2026-09-01','Isi saldo e-wallet'),
  ((SELECT id FROM wallets WHERE kind='bank' ORDER BY id LIMIT 1),(SELECT id FROM wallets WHERE kind='ewallet' ORDER BY id LIMIT 1),1000000,'2026-09-15','Isi saldo e-wallet');
INSERT INTO budgets (category_id, month, amount) VALUES
  ((SELECT id FROM categories WHERE name='Makan' AND type='expense'),'2026-09',2000000),((SELECT id FROM categories WHERE name='Tagihan' AND type='expense'),'2026-09',1300000),
  ((SELECT id FROM categories WHERE name='Transport' AND type='expense'),'2026-09',1000000),((SELECT id FROM categories WHERE name='Belanja' AND type='expense'),'2026-09',700000),
  ((SELECT id FROM categories WHERE name='Hiburan' AND type='expense'),'2026-09',600000);
INSERT INTO goals (name, emoji, target, saved_before, deadline) VALUES
  ('Dana darurat','🛟',15000000,0,'2027-06'),('Laptop baru','💻',12000000,0,'2027-01'),('Liburan akhir tahun','🌴',5000000,0,'2026-12');
INSERT INTO goal_deposits (goal_id, wallet_id, amount, date, note) VALUES
  ((SELECT id FROM goals WHERE name='Dana darurat'),(SELECT id FROM wallets WHERE kind='bank' ORDER BY id LIMIT 1),1500000,'2026-04-05','Setoran bulanan'),
  ((SELECT id FROM goals WHERE name='Dana darurat'),(SELECT id FROM wallets WHERE kind='bank' ORDER BY id LIMIT 1),1500000,'2026-05-05','Setoran bulanan'),
  ((SELECT id FROM goals WHERE name='Dana darurat'),(SELECT id FROM wallets WHERE kind='bank' ORDER BY id LIMIT 1),1500000,'2026-06-05','Setoran bulanan'),
  ((SELECT id FROM goals WHERE name='Dana darurat'),(SELECT id FROM wallets WHERE kind='bank' ORDER BY id LIMIT 1),1500000,'2026-07-05','Setoran bulanan'),
  ((SELECT id FROM goals WHERE name='Dana darurat'),(SELECT id FROM wallets WHERE kind='bank' ORDER BY id LIMIT 1),1500000,'2026-08-05','Setoran bulanan'),
  ((SELECT id FROM goals WHERE name='Laptop baru'),(SELECT id FROM wallets WHERE kind='bank' ORDER BY id LIMIT 1),1400000,'2026-06-05','Setoran bulanan'),
  ((SELECT id FROM goals WHERE name='Laptop baru'),(SELECT id FROM wallets WHERE kind='bank' ORDER BY id LIMIT 1),1400000,'2026-07-05','Setoran bulanan'),
  ((SELECT id FROM goals WHERE name='Laptop baru'),(SELECT id FROM wallets WHERE kind='bank' ORDER BY id LIMIT 1),1400000,'2026-08-05','Setoran bulanan'),
  ((SELECT id FROM goals WHERE name='Liburan akhir tahun'),(SELECT id FROM wallets WHERE kind='bank' ORDER BY id LIMIT 1),600000,'2026-07-05','Setoran bulanan'),
  ((SELECT id FROM goals WHERE name='Liburan akhir tahun'),(SELECT id FROM wallets WHERE kind='bank' ORDER BY id LIMIT 1),600000,'2026-08-05','Setoran bulanan'),
  ((SELECT id FROM goals WHERE name='Dana darurat'),(SELECT id FROM wallets WHERE kind='bank' ORDER BY id LIMIT 1),1000000,'2026-09-28','Setoran bulanan'),
  ((SELECT id FROM goals WHERE name='Laptop baru'),(SELECT id FROM wallets WHERE kind='bank' ORDER BY id LIMIT 1),500000,'2026-09-28','Setoran bulanan'),
  ((SELECT id FROM goals WHERE name='Liburan akhir tahun'),(SELECT id FROM wallets WHERE kind='bank' ORDER BY id LIMIT 1),300000,'2026-09-28','Setoran bulanan');
COMMIT;
